---
- name: networking | install bridge-utils
  package:
    name: bridge-utils
    state: present

- name: networking | remove installer config
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent
  notify: restart networking

- name: networking | install netplan configuration
  template:
    src: 99-network.yaml
    dest: /etc/netplan/
  notify: restart networking
  
# - name: networking | configure interfaces
#   template:
#     src: interfaces
#     dest: /etc/network/interfaces
#   notify: restart networking

- name: networking | enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: networking | turn on fq_codel as default qdisc
  sysctl:
    name: net.core.default_qdisc
    value: fq_codel

- name: networking | expand ephemeral port range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "1024 65535"

- name: networking | enable ecn
  sysctl:
    name: net.ipv4.tcp_ecn
    value: 1
