---
- name: networking | install bridge-utils
  package: name=bridge-utils state=installed

- name: networking | configure interfaces
  template: src=interfaces dest=/etc/network/interfaces
  notify: restart networking

- name: networking | enable ip forwarding
  sysctl: name=net.ipv4.ip_forward value=1

- name: networking | setup pulse8 provider
  copy: src=provider dest=/etc/ppp/peers/provider mode=0640
  notify: restart networking

- name: networking | turn on fq_codel as default qdisc
  sysctl: name=net.core.default_qdisc value=fq_codel
  notify: restart networking

- name: networking | remove ppp-ethtool
  file: path=/etc/ppp/ip-up.d/ethtool state=absent

- name: networking | expand ephemeral port range
  sysctl: name=net.ipv4.ip_local_port_range value="1024 65535"

- name: networking | copy shorewall restart script to ppp ip-up.d
  copy: src=shorewall dest=/etc/ppp/ip-up.d/shorewall mode=0755

- name: networking | disable log martians
  sysctl: name=net.ipv4.conf.{{ item }}.log_martians value=0
  with_items:
  - enp0s20f1

- name: networking | enable ecn
  sysctl: name=net.ipv4.tcp_ecn value=1
