---
- hosts: routers
  become: yes
  roles:
    - { role: system, tags: system }
    # - { role: wireguard, tags: wireguard }
    - { role: networking, tags: networking }
    - { role: firewall, tags: firewall }
    - { role: dns, tags: dns }
    - { role: dhcp, tags: dhcp }
    - { role: unifi, tags: unifi }
