---
- hosts: routers
  become: yes
  roles:
    - { role: system, tags: system }
    - { role: networking, tags: networking }
    - { role: firewall, tags: firewall }
    - { role: dns, tags: dns }
    - { role: dhcp, tags: dhcp }
    - { role: ipsec, tags: ipsec }
