#!/bin/sh

modprobe sch_cake
modprobe act_mirred

iface="enp0s20f0"
outbound="bandwidth 38mbit"
inbound="bandwidth 380mbit"

tc qdisc del dev $iface root 2>/dev/null || true
tc qdisc add dev $iface root cake $outbound besteffort nat docsis regional

if ! ip link show ifb4${iface} > /dev/null; then
    ip link add name ifb4${iface} type ifb
fi

tc qdisc del dev $iface handle ffff: ingress 2>/dev/null || true
tc qdisc add dev $iface handle ffff: ingress

tc qdisc del dev ifb4${iface} root 2>/dev/null || true
tc qdisc add dev ifb4${iface} root cake $inbound besteffort nat docsis regional

ip link set dev ifb4${iface} up

tc filter add dev $iface parent ffff: protocol all prio 10 u32 \
    match u32 0 0 flowid 1:1 action mirred egress redirect dev ifb4${iface}
