---
- name: system | enable persistent journal log
  copy: src=journald.conf dest=/etc/systemd/journald.conf
  notify: restart journald

# Unstable repo used only for wireguard. The limit-unstable file
# prevents packages from inadvertently coming from unstable unless
# explicitly installed.
- copy: src=limit-unstable dest=/etc/apt/preferences.d/

- apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    state: present

- name: system | setup apt sources
  copy: src=sources.list dest=/etc/apt/sources.list
  register: r

- name: system | update apt
  command: apt update
  when: r is changed

- name: system | install useful packages
  package: name={{ item }} state=present
  with_items:
    - vim
    - tmux
    - conntrack
    - htop
    - curl

- name: system | install intel microcode updates
  package: name=intel-microcode state=present

- name: system | install unattended upgrades
  package: name={{ item }} state=present
  with_items:
    - unattended-upgrades

- name: system | install chrony
  package: name=chrony state=present

- name: system | enable chrony
  service: name=chrony enabled=yes

- name: system | remove smartmontools - doesn't work on mmc
  package: name=smartmontools state=absent

- name: system | configure unattended upgrades
  template: src={{ item }} dest=/etc/apt/apt.conf.d/{{ item }}
  with_items:
    - 50unattended-upgrades
    - 20auto-upgrades
