---
- name: system | enable persistent journal log
  copy: src=journald.conf dest=/etc/systemd/journald.conf
  notify: restart journald

- name: system | setup apt sources
  copy: src=sources.list dest=/etc/apt/sources.list
  register: r

- name: system | update apt
  command: apt update
  when: r|changed

- name: system | install useful packages
  package: name={{ item }} state=present
  with_items:
    - vim
    - tmux
    - conntrack
    - htop
    - curl

- name: system | install intel microcode updates
  package: name=intel-microcode state=present

- name: system | install unattended upgrades
  package: name={{ item }} state=present
  with_items:
    - unattended-upgrades

- name: system | install chrony
  package: name=chrony state=present

- name: system | enable chrony
  service: name=chrony enabled=yes

- name: system | configure unattended upgrades
  copy: src={{ item }} dest=/etc/apt/apt.conf.d/{{ item }}
  with_items:
    - 50unattended-upgrades
    - 20auto-upgrades
