---
- name: system | install useful packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - tmux
    - conntrack
    - htop
    - curl
    - python3-pip

- name: system | configure unattended upgrades
  template:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/{{ item }}
  with_items:
    - 50unattended-upgrades
    - 20auto-upgrades

- name: system | install rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    mode: 0755
  notify:
    - exec rc.local
