- name: monitoring | download installation script
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: ~/kickstart.sh
    mode: +x

- name: monitoring | run installation script
  command: ~/kickstart.sh --dont-wait

- name: monitoring | cleanup installation script
  file:
    path: ~/kickstart.sh
    state: absent

- name: monitoring | netdata config
  template:
    src: netdata.conf
    dest: /etc/netdata/
  notify: restart netdata

- name: monitoring | start and enable netdata
  service:
    name: netdata
    state: started
    enabled: yes
