---
- name: firewall | install shorewall
  package: name=shorewall state=present

- name: firewall | shorewall defaults
  copy: src=etc_default_shorewall dest=/etc/default/shorewall
  notify:
    - check shorewall
    - reload shorewall

- name: firewall | shorewall conf
  copy: src=shorewall.conf dest=/etc/shorewall/shorewall.conf
  notify:
    - check shorewall
    - reload shorewall

- name: firewall | remove old files
  file: state=absent path=/etc/shorewall/{{ item }}
  with_items:
    - init
    - tcclasses
    - tcdevices
  notify:
    - check shorewall
    - reload shorewall

- name: firewall | shorewall config files
  template: src={{ item }} dest=/etc/shorewall/{{ item }}
  with_items:
    - snat
    - interfaces
    - policy
    - zones
    - rules
    - tcstart
    - tunnels
    - hosts
  notify:
    - check shorewall
    - reload shorewall

- name: firewall | enable shorewall
  service: name=shorewall enabled=yes state=started
