---
- name: unifi | create directories
  file:
    path: /opt/unifi
    state: directory
    mode: 0755

- name: unifi | stop and remove existing container
  docker_container:
    name: unifi
    state: absent

- name: unifi | pull latest unifi image
  docker_image:
    name: linuxserver/unifi-controller:latest
    source: pull

- name: unifi | create and start container
  docker_container:
    name: unifi
    image: linuxserver/unifi-controller:latest
    published_ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
    volumes:
      - /opt/unifi:/config
    networks:
      - name: bridge
        aliases:
          - unifi
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
