---
- name: dns | install server
  package: name=unbound state=present

- name: dns | copy defaults config
  copy: src=unbound dest=/etc/default/unbound
  notify: restart unbound

- name: dns | copy home config
  copy: src=home.conf dest=/etc/unbound/unbound.conf.d/home.conf
  notify: restart unbound

- name: unbound | enable unbound server
  service: name=unbound enabled=yes
