---
- name: dns | install server
  package:
    name: unbound
    state: present

- name: dns | copy server config
  template:
    src: server.conf
    dest: /etc/unbound/unbound.conf.d/
  notify: restart unbound

- name: dns | copy home zone config
  template:
    src: home.conf
    dest: /etc/unbound/unbound.conf.d/
  notify: restart unbound

- name: dns | enable unbound server
  service:
    name: unbound
    enabled: yes

- name: dns | disable systemd-resolved :53
  copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
  notify: restart systemd-resolved
