- name: docker | create docker directory
  file: "path={{ item }} state=directory mode=0775 owner=root group=root"
  with_items:
    - /etc/docker

- name: docker | copy daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0775
    force: yes
  notify:
    - restart docker

- name: docker | uninstall docker-py
  pip:
    name: docker-py
    state: absent

- name: docker | add gpg signing key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: docker | add official repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker
    update_cache: yes

- name: docker | install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: present

- name: docker | install docker pip module
  pip:
    name: docker
    state: latest

- name: docker | start and enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: docker | register docker networks
  shell: docker network ls --format '{{ '{{' }} .Name{{ '}}' }}'
  register: docker_networks

- name: docker | create docker network
  docker_network:
    name: hamster
    state: present
  when: ('hamster' not in docker_networks.stdout_lines)

- name: docker | remove all unused images
  shell: docker image prune -af &> /dev/null || true
  ignore_errors: yes

- name: docker | remove all unused volumes
  shell: docker volume prune -f &> /dev/null || true
  ignore_errors: yes
