global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
- '/etc/prometheus/*-rules.yml'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["localhost:9093"]
